// Real AI-made browser games scraped from itch.io AI Game Jams (2026)
// All playable in browser, all made with AI assistance

export const realGames = [
  {
    slug: 'rogue-memory',
    title: 'Rogue Memory',
    developer: 'quantumcodemonk',
    genre: 'Dungeon Crawler',
    tagline: "A first-person dungeon crawler set inside a dying AI's corrupted memory.",
    playUrl: 'https://quantumcodemonk.itch.io/rogue-memory',
    source: 'AI Browser Game Jam',
    rating: 4.0,
  },
  {
    slug: '6-bit-vanguard',
    title: '6-bit Vanguard (Star Overlord 4.0)',
    developer: 'Battle_of_the_moon',
    genre: 'Retro Shooter',
    tagline: 'Have you ever wondered what space would look like filtered through a Game Boy?',
    playUrl: 'https://battle-of-the-moon.itch.io/6-bit-vanguard',
    source: 'AI Browser Game Jam',
    rating: 4.0,
  },
  {
    slug: 'link-state',
    title: 'Link State',
    developer: 'bml',
    genre: 'Action / Puzzle',
    tagline: 'Traverse a hostile operating system as a rogue data packet to reach the User.',
    playUrl: 'https://bml.itch.io/link-state',
    source: 'AI Browser Game Jam',
    rating: 3.8,
  },
  {
    slug: 'marble-garble',
    title: 'MARBLE GARBLE',
    developer: 'Daniel__BK',
    genre: 'Physics Puzzle',
    tagline: 'Take control of the marble in a world where physics is your best friend and worst enemy.',
    playUrl: 'https://daniel-bk.itch.io/marble-garble',
    source: 'AI Browser Game Jam',
    rating: 3.75,
  },
  {
    slug: 'spell-cascade',
    title: 'Spell Cascade',
    developer: 'yurukusa',
    genre: 'Survivor-like',
    tagline: 'Chain skills, discover synergies, survive 10 minutes. 143 hand-tuned improvements.',
    playUrl: 'https://yurukusa.itch.io/spell-cascade',
    source: 'AI Browser Game Jam',
    rating: 3.5,
  },
  {
    slug: 'glitch-circuit',
    title: 'Glitch Circuit',
    developer: 'RogueSoulX',
    genre: 'Arcade Runner',
    tagline: 'Navigate twisted terrain and glitching enemies in this fast-paced arcade runner.',
    playUrl: 'https://roguesoulx.itch.io/glitch-circuit',
    source: 'AI Browser Game Jam',
    rating: 3.25,
  },
  {
    slug: 'ghost-shift',
    title: 'Ghost Shift',
    developer: 'Focaccai',
    genre: 'Horror / Stealth',
    tagline: 'The art is fake but the danger is real.',
    playUrl: 'https://focaccai.itch.io/ghost-shift',
    source: 'AI Browser Game Jam',
    rating: 2.75,
  },
  {
    slug: 'potus-election-sim',
    title: 'POTUS - Election Simulator',
    developer: 'Dackers Studios',
    genre: 'Simulation',
    tagline: "Build your candidate's backstory, battle through the primaries, fight for 270.",
    playUrl: 'https://dackers-studios.itch.io/potus-2024',
    source: 'AI Browser Game Jam',
    rating: 2.75,
  },
  {
    slug: 'pyramid-wars',
    title: 'Pyramid Wars',
    developer: 'Durian Arcade',
    genre: 'RTS / Clicker',
    tagline: 'RTS Clicker with Boosterpacks.',
    playUrl: 'https://durian-arcade.itch.io/pyramid-wars',
    source: 'AI Browser Game Jam 3',
    rating: 0,
  },
  {
    slug: 'grand-hotel-tycoon',
    title: 'Grand Hotel Tycoon',
    developer: 'WildGameStudio',
    genre: 'Tycoon / Management',
    tagline: 'Build and run your dream hotel. Hire staff, manage guests, chase 5 stars.',
    playUrl: 'https://wildgamestudio.itch.io/grand-hotel-tycoon',
    source: 'AI Browser Game Jam 3',
    rating: 0,
  },
  {
    slug: 'house-of-loki',
    title: 'House of Loki',
    developer: 'Unifiedesign',
    genre: 'Bullet Hell / Roguelite',
    tagline: "Roll the dice and delve deeper under Loki's Casino in this bullet-hell roguelite.",
    playUrl: 'https://unifiedesign-games.itch.io/house-of-loki',
    source: 'AI Browser Game Jam 3',
    rating: 0,
  },
  {
    slug: 'wagon-bones',
    title: 'Wagon Bones',
    developer: 'voltron2112',
    genre: 'Roguelike / Dice',
    tagline: 'A Balatro-inspired dice roguelike set on the Oregon Trail.',
    playUrl: 'https://voltron2112.itch.io/wagon-bones',
    source: 'AI Browser Game Jam 3',
    rating: 0,
  },
  {
    slug: 'pixel-monster',
    title: 'Pixel Monster',
    developer: 'LEN0121',
    genre: 'Virtual Pet / RPG',
    tagline: 'Raise, evolve, battle, and collect pixel monsters in a virtual pet RPG.',
    playUrl: 'https://len0121.itch.io/pixel-monster',
    source: 'AI Browser Game Jam 3',
    rating: 0,
  },
  {
    slug: 'data-drop',
    title: 'Data Drop',
    developer: 'AwesomistGames',
    genre: 'Puzzle / Hacking',
    tagline: 'The hacking, stacking, and cracking game.',
    playUrl: 'https://awesomistgames.itch.io/data-drop',
    source: 'AI Browser Game Jam 3',
    rating: 0,
  },
  {
    slug: 'brainrot-merge',
    title: 'Brainrot Merge',
    developer: 'mrGabas',
    genre: 'Merge / Casual',
    tagline: 'A chaotic meme Suika game with roguelike perks and permanent upgrades.',
    playUrl: 'https://mrgabas.itch.io/brainrot-merge',
    source: 'AI Browser Game Jam 3',
    rating: 0,
  },
  {
    slug: 'spicefall-command',
    title: 'Spicefall Command',
    developer: 'Bitten Heart Studio',
    genre: 'RTS / Strategy',
    tagline: 'A fast browser RTS about resource pressure, base building, and desert skirmish warfare.',
    playUrl: 'https://bitten-heart-studio.itch.io/spicefall-command',
    source: 'AI Browser Game Jam 3',
    rating: 0,
  },
  {
    slug: 'star-conquest',
    title: 'Star Conquest - Era I: The Cradle',
    developer: 'kenjaminGames',
    genre: '4X / Strategy',
    tagline: "Humanity's solar system is yours to win. Colonize it, out-trade your rivals.",
    playUrl: 'https://kenjamingames.itch.io/star-conquest',
    source: 'AI Browser Game Jam 3',
    rating: 0,
  },
  {
    slug: 'my-island',
    title: 'My-Island',
    developer: 'MaoKoroku',
    genre: 'City Builder / Cozy',
    tagline: 'A cozy tropical island city-builder. Build, collect, and grow your paradise.',
    playUrl: 'https://maokoroku.itch.io/my-island',
    source: 'AI Browser Game Jam 3',
    rating: 0,
  },
  {
    slug: 'one-page-rpg',
    title: 'One-Page RPG - Tiny Roguelike',
    developer: 'namigk',
    genre: 'Roguelike',
    tagline: 'A complete roguelike packed into a single screen. Descend floors, fight monsters.',
    playUrl: 'https://namigk.itch.io/one-page-rpg',
    source: 'AI Browser Game Jam 3',
    rating: 0,
  },
  {
    slug: 'the-regulars',
    title: 'THE REGULARS',
    developer: 'H A F F N E R V I S I O N',
    genre: 'Mystery / Pixel Art',
    tagline: 'A cozy pixel-art memory-mystery: tend a diner counter as the town quietly forgets.',
    playUrl: 'https://granthaffner.itch.io/the-regulars',
    source: 'AI Browser Game Jam 3',
    rating: 0,
  },
  {
    slug: 'snow-bunny',
    title: 'Snow Bunny',
    developer: 'Focaccai',
    genre: 'Arcade',
    tagline: 'A rabbit rides a broom down a snowy mountain.',
    playUrl: 'https://focaccai.itch.io/snow-bunny',
    source: 'AI Browser Game Jam 3',
    rating: 0,
  },
  {
    slug: 'mansion-of-secrets',
    title: 'Mansion of Secrets',
    developer: 'HD Expanse',
    genre: 'Horror / Stealth',
    tagline: 'Search. Sabotage. Survive.',
    playUrl: 'https://hdgames2484.itch.io/mansion-of-secrets',
    source: 'AI Browser Game Jam 3',
    rating: 0,
  },
  {
    slug: 'neuro-malla',
    title: 'NEURO·MALLA',
    developer: 'Vantix Digital Studios',
    genre: 'Action / Medical',
    tagline: 'You are the brain. Heal. Purge. Survive.',
    playUrl: 'https://vantix-digital-studios.itch.io/neuro-malla',
    source: 'AI Browser Game Jam 3',
    rating: 0,
  },
  {
    slug: 'the-ship-remembers',
    title: 'The Ship Remembers',
    developer: 'Divine950',
    genre: 'Narrative / Survival',
    tagline: 'Keep an old patrol ship alive as dead routes, old voices, and pirate fire close in.',
    playUrl: 'https://divine950.itch.io/the-ship-remembers',
    source: 'AI Browser Game Jam 3',
    rating: 0,
  },
  {
    slug: 'meow-match-cafe',
    title: 'Meow Match Cafe',
    developer: 'immasam',
    genre: 'Match Puzzle / Casual',
    tagline: 'Match cute kittens and bakes to run a cozy cafe. A sweet hyper-casual match puzzle.',
    playUrl: 'https://immasam.itch.io/meow-match-cafe',
    source: 'AI Browser Game Jam 3',
    rating: 0,
  },
]
